name: venv
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - nltk
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - scikit-learn
  - pytorch
  - pip:
    - NRCLex
    - Django
    - transformers
    - sentencepiece
    - regex
  