# Generated by Django 4.2.7 on 2023-11-22 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawTextDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('raw_text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TextAnalyzer.rawtextdatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionalAnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_category', models.CharField(max_length=50)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('raw_text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TextAnalyzer.rawtextdatamodel')),
            ],
        ),
    ]
